export const ADD_SUBMIT_START = "ADD_SUBMIT_START";
export const ADD_SUBMIT_SUCCESS = "ADD_SUBMIT_SUCCESS";
export const ADD_SUBMIT_FAIL = "ADD_SUBMIT_FAIL";

export const LOAD_CALENDAR_EVENTS_START = "LOAD_CALENDAR_EVENTS_START";
export const LOAD_CALENDAR_EVENTS_SUCCESS = "LOAD_CALENDAR_EVENTS_SUCCESS";
export const LOAD_CALENDAR_EVENTS_FAIL = "LOAD_CALENDAR_EVENTS_FAIL";

export const DELETE_CALENDAR_EVENT_START = "DELETE_CALENDAR_EVENT_START";
export const DELETE_CALENDAR_EVENT_SUCCESS = "DELETE_CALENDAR_EVENT_SUCCESS";
export const DELETE_CALENDAR_EVENT_FAIL = "DELETE_CALENDAR_EVENT_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
